# Generated by Django 2.2.4 on 2019-08-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blog_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
