# Generated by Django 2.2.4 on 2019-08-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20190808_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
