# Generated by Django 2.2.4 on 2019-08-09 14:20

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20190809_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to=board.models.get_memo_image_path),
        ),
    ]
