# Generated by Django 2.2.4 on 2019-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
