# Generated by Django 2.2.2 on 2019-08-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_post_image'),
        ('board', '0012_auto_20190809_2138'),
    ]

    operations = [
    ]
