# Generated by Django 2.2.2 on 2019-08-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_merge_20190810_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.TextField(max_length=15, null=True),
        ),
    ]
